# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'VehicleTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VehicleTracker
  pod 'Firebase/Core'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  # pod 'GoogleAppMeasurement', '~> 5.2.0'

  target 'VehicleTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
